-- Create site_settings table
CREATE TABLE IF NOT EXISTS public.site_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key TEXT NOT NULL UNIQUE,
    value JSONB NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;

-- Create policies (Allow read for everyone, write for authenticated users/admins)
-- For this demo/simple app, we'll allow public read.
CREATE POLICY "Allow public read access" ON public.site_settings
    FOR SELECT USING (true);

CREATE POLICY "Allow authenticated update access" ON public.site_settings
    FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Allow authenticated insert access" ON public.site_settings
    FOR INSERT WITH CHECK (auth.role() = 'authenticated');

-- Insert default configuration
INSERT INTO public.site_settings (key, value)
VALUES (
    'home_config',
    '{
        "scrollSensitivity": 1500,
        "zoomLevel": 1.1,
        "transitionDuration": 700,
        "overlayOpacity": 0.7,
        "blurAmount": 5,
        "steps": [
            {
                "title": "Hızlı Teslim",
                "desc": "7-21 gün arasında net teslim süreleri. Gecikme yok.",
                "icon": "Clock"
            },
             {
                "title": "Sabit Fiyat",
                "desc": "Sürpriz maliyetler olmadan, önceden belirlenmiş net fiyatlar.",
                "icon": "Tag"
            },
             {
                "title": "Profesyonel Akış",
                "desc": "WeTransfer ile yükleyin, panelden adım adım takip edin.",
                "icon": "Film"
            },
             {
                "title": "Teknik Standart",
                "desc": "4K/LOG ve 1080p/Rec709 desteği ile yüksek kalite.",
                "icon": "CheckCircle"
            }
        ],
        "scenes": [
            {
                "id": 1,
                "type": "card",
                "title": "1. Dosyalarını Yükle",
                "desc": "Ham görüntülerinizi WeTransfer veya Google Drive üzerinden bize gönderin.",
                "img": "https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=1600"
            },
            {
                "id": 2,
                "type": "card",
                "title": "2. Profesyonel Kurgu",
                "desc": "Uzman ekibimiz görüntülerinizi sinematik filme dönüştürsün.",
                "img": "https://images.unsplash.com/photo-1574717432741-9346d6d43329?auto=format&fit=crop&q=80&w=1600"
            },
            {
                "id": 3,
                "type": "card",
                "title": "3. Revize & Onay",
                "desc": "Taslağı izleyin, beğenmediğiniz yerleri panelden saniye saniye not edin.",
                "img": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=1600"
            },
            {
                "id": 4,
                "type": "card",
                "title": "4. Teslimat",
                "desc": "Final filminizi 4K kalitesinde indirin ve sosyal medyada paylaşın.",
                "img": "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=1600"
            }
        ]
    }'::jsonb
) ON CONFLICT (key) DO NOTHING;
